from gym.envs.toy_text.blackjack import BlackjackEnv
from gym.envs.toy_text.roulette import RouletteEnv
from gym.envs.toy_text.frozen_lake import FrozenLakeEnv
from gym.envs.toy_text.nchain import NChainEnv
from gym.envs.toy_text.hotter_colder import HotterColder
from gym.envs.toy_text.guessing_game import GuessingGame
from gym.envs.toy_text.kellycoinflip import KellyCoinflipEnv
from gym.envs.toy_text.kellycoinflip import KellyCoinflipGeneralizedEnv
from gym.envs.toy_text.cliffwalking import CliffWalkingEnv
from gym.envs.toy_text.bitflip import BitFlipEnv
from gym.envs.toy_text.indep_bandit import IndependentBanditEnv
from gym.envs.toy_text.easy_bandit import EasyBanditEnv
from gym.envs.toy_text.medium_bandit import MediumBanditEnv
from gym.envs.toy_text.hard_bandit import HardBanditEnv
from gym.envs.toy_text.uniform_bandit import UniformBanditEnv